{% set name = "gradio" %}
{% set version = "5.49.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gradio-{{ version }}.tar.gz
  sha256: c06faa324ae06c3892c8b4b4e73c706c4520d380f6b9e52a3c02dc53a7627ba9
  # url: https://github.com/gradio-app/gradio/archive/gradio@{{ version }}.tar.gz


build:
  entry_points:
    - gradio = gradio.cli:cli
    - upload_theme = gradio.themes.upload_theme:main
  skip: true  # [py<310]
  number: 0

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-requirements-txt
    - hatch-fancy-pypi-readme >=22.5.0
  run:
    - python
    - aiofiles >=22.0,<25.0
    - anyio >=3.0,<5.0
    # this is a replacement for the built-in 'audioop' module removed in Python 3.13 (and needed for pydub)
    - audioop-lts <1.0  # [py>=313]
    - brotli-python >=1.1.0
    - fastapi >=0.115.2,<1.0
    - ffmpy
    - groovy-python >=0.1,<0.2
    - gradio-client ==1.13.3
    - httpx >=0.24.1,<1.0
    - huggingface_hub >=0.33.5,<2.0
    - Jinja2 <4.0
    - markupsafe >=2.0,<4.0
    - numpy >=1.0,<3.0
    - orjson >=3.0,<4.0
    - packaging
    - pandas >=1.0,<3.0
    - pillow >=8.0,<12.0
    - pydantic >=2.0,<2.12
    - python-multipart >=0.0.18 # required for fastapi forms.
    - pydub
    - pyyaml >=5.0,<7.0
    - ruff >=0.9.3 # needed here for custom component docs generation
    - safehttpx >=0.1.6,<0.2.0
    - semantic_version >=2.0,<3.0
    - starlette >=0.40.0,<1.0
    - tomlkit >=0.12.0,<0.14.0
    - typer >=0.12,<1.0
    - typing_extensions >=4.0,<5.0
    - uvicorn >=0.14.0

test:
  imports:
    - gradio
  commands:
    - pip check
    - gradio --help
    - upload_theme --help
  requires:
    - pip

about:
  home: https://www.gradio.app/
  dev_url: https://github.com/gradio-app/gradio
  doc_url: https://www.gradio.app/
  summary: Python library for easily interacting with trained machine learning models
  description: |
    Gradio is an open-source Python package that allows you to quickly build a demo or web application
    for your machine learning model, API, or any arbitrary Python function.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache

extra:
  recipe-maintainers:
    - jeongseok-meta
    - abidlabs
    - Sclare87
